KERNEL_BUSSES_ADDONS_DIR := $(KERNEL_ADDONS_DIR)/busses
KERNEL_BUSSES_ADDONS_BUILD_DIR := $(KERNEL_ADDONS_BUILD_DIR)/busses

# include sub makefiles
include $(addsuffix /makefile, $(addprefix $(KERNEL_BUSSES_ADDONS_DIR)/, \
	ide \
))
