# libc hoard makefile
LIBC_HOARD_DIR := hoard

MY_OBJS += \
	$(LIBC_HOARD_DIR)/arch-specific.o \
	$(LIBC_HOARD_DIR)/processheap.o \
	$(LIBC_HOARD_DIR)/heap.o \
	$(LIBC_HOARD_DIR)/superblock.o \
	$(LIBC_HOARD_DIR)/threadheap.o \
	$(LIBC_HOARD_DIR)/wrapper.o
