# arch ARM makefile
KERNEL_ARCH_ARM_DIR := arch/arm

MY_SRCS += \
	$(KERNEL_ARCH_ARM_DIR)/arch_asm.s \
	$(KERNEL_ARCH_ARM_DIR)/arch_cpu.c \
	$(KERNEL_ARCH_ARM_DIR)/arch_dbg_console.c \
	$(KERNEL_ARCH_ARM_DIR)/arch_debug.c \
	$(KERNEL_ARCH_ARM_DIR)/arch_elf.c \
	$(KERNEL_ARCH_ARM_DIR)/arch_faults.c \
	$(KERNEL_ARCH_ARM_DIR)/arch_int.c \
	$(KERNEL_ARCH_ARM_DIR)/arch_interrupts.c \
	$(KERNEL_ARCH_ARM_DIR)/arch_smp.c \
	$(KERNEL_ARCH_ARM_DIR)/arch_thread.c \
	$(KERNEL_ARCH_ARM_DIR)/arch_time.c \
	$(KERNEL_ARCH_ARM_DIR)/arch_timer.c \
	$(KERNEL_ARCH_ARM_DIR)/arch_vm.c \
	$(KERNEL_ARCH_ARM_DIR)/arch_vm_translation_map.c
