# dev i386 floppy makefile
MY_SRCDIR := $(GET_LOCAL_DIR)
MY_TARGETDIR := $(call TOBUILDDIR, $(MY_SRCDIR))
MY_TARGET := $(MY_TARGETDIR)/floppy

MY_SRCS := \
	floppy.c

include templates/kernel_addons.mk
