# libc stdio makefile
LIBC_STDIO_DIR := stdio

MY_SRCS += \
	$(LIBC_STDIO_DIR)/stdio.c \
	$(LIBC_STDIO_DIR)/_v_printf.c \
	$(LIBC_STDIO_DIR)/vsprintf.c \
    $(LIBC_STDIO_DIR)/vfprintf.c \
    $(LIBC_STDIO_DIR)/_v_scanf.c 
