# app makefile
MY_SRCDIR := $(GET_LOCAL_DIR)

MY_SRCS := \
	commands.c \
	main.c \
	parse.c \
	statements.c \
	shell_vars.c \
	file_utils.c \
	script.c \
	args.c

MY_LIBS := -lc -lnewos -lsupc++

include templates/app.mk

