# libc unistd makefile
LIBC_UNISTD_DIR := unistd

MY_SRCS += \
	$(LIBC_UNISTD_DIR)/chdir.c \
	$(LIBC_UNISTD_DIR)/close.c \
	$(LIBC_UNISTD_DIR)/dup.c \
	$(LIBC_UNISTD_DIR)/dup2.c \
	$(LIBC_UNISTD_DIR)/fsync.c \
	$(LIBC_UNISTD_DIR)/getcwd.c \
	$(LIBC_UNISTD_DIR)/getpgid.c \
	$(LIBC_UNISTD_DIR)/getpgrp.c \
	$(LIBC_UNISTD_DIR)/getsid.c \
	$(LIBC_UNISTD_DIR)/ioctl.c \
	$(LIBC_UNISTD_DIR)/lseek.c \
	$(LIBC_UNISTD_DIR)/open.c \
	$(LIBC_UNISTD_DIR)/pipe.c \
	$(LIBC_UNISTD_DIR)/pread.c \
	$(LIBC_UNISTD_DIR)/pwrite.c \
	$(LIBC_UNISTD_DIR)/read.c \
	$(LIBC_UNISTD_DIR)/setpgid.c \
	$(LIBC_UNISTD_DIR)/setpgrp.c \
	$(LIBC_UNISTD_DIR)/setsid.c \
	$(LIBC_UNISTD_DIR)/signal.c \
	$(LIBC_UNISTD_DIR)/sleep.c \
	$(LIBC_UNISTD_DIR)/sync.c \
	$(LIBC_UNISTD_DIR)/unlink.c \
	$(LIBC_UNISTD_DIR)/usleep.c \
	$(LIBC_UNISTD_DIR)/write.c
