#ifdef ARCH_i386
#include "i386/rldreloc.inc"
#endif
#ifdef ARCH_x86_64
#include "x86_64/rldreloc.inc"
#endif
#ifdef ARCH_alpha
#include "alpha/rldreloc.inc"
#endif
#ifdef ARCH_sh4
#include "sh4/rldreloc.inc"
#endif
#ifdef ARCH_sparc
#include "sparc/rldreloc.inc"
#endif
#ifdef ARCH_sparc64
#include "sparc64/rldreloc.inc"
#endif
#ifdef ARCH_mips
#include "mips/rldreloc.inc"
#endif
#ifdef ARCH_ppc
#include "ppc/rldreloc.inc"
#endif
