KERNEL_DEV_ADDONS_DIR := $(KERNEL_ADDONS_DIR)/dev
KERNEL_DEV_ADDONS_BUILD_DIR := $(KERNEL_ADDONS_BUILD_DIR)/dev

# include sub makefiles
include $(addsuffix /makefile, $(addprefix $(KERNEL_DEV_ADDONS_DIR)/, \
	disk \
))
