# arch SH4 makefile
KERNEL_ARCH_SH4_DIR := arch/SH4

MY_OBJS += \
	$(KERNEL_ARCH_SH4_DIR)/arch_asm.o \
	$(KERNEL_ARCH_SH4_DIR)/arch_cpu.o \
	$(KERNEL_ARCH_SH4_DIR)/arch_dbg_console.o \
	$(KERNEL_ARCH_SH4_DIR)/arch_debug.o \
	$(KERNEL_ARCH_SH4_DIR)/arch_faults.o \
	$(KERNEL_ARCH_SH4_DIR)/arch_int.o \
	$(KERNEL_ARCH_SH4_DIR)/arch_smp.o \
	$(KERNEL_ARCH_SH4_DIR)/arch_timer.o \
	$(KERNEL_ARCH_SH4_DIR)/arch_thread.o \
	$(KERNEL_ARCH_SH4_DIR)/arch_vm.o \
	$(KERNEL_ARCH_SH4_DIR)/arch_vm_translation_map.o
