# libc hoard makefile
LIBC_HOARD_DIR := hoard

MY_SRCS += \
	$(LIBC_HOARD_DIR)/arch-specific.cpp \
	$(LIBC_HOARD_DIR)/processheap.cpp \
	$(LIBC_HOARD_DIR)/heap.cpp \
	$(LIBC_HOARD_DIR)/superblock.cpp \
	$(LIBC_HOARD_DIR)/threadheap.cpp \
	$(LIBC_HOARD_DIR)/wrapper.cpp
