KERNEL_BUSSES_IDE_ADDONS_DIR := $(KERNEL_BUSSES_ADDONS_DIR)/ide
KERNEL_BUSSES_IDE_ADDONS_BUILD_DIR := $(KERNEL_BUSSES_ADDONS_BUILD_DIR)/ide

# include sub makefiles
include $(addsuffix /makefile, $(addprefix $(KERNEL_BUSSES_IDE_ADDONS_DIR)/, \
	ide_isa \
))
