# net makefile
KERNEL_NET_DIR := net

MY_OBJS += \
	$(KERNEL_NET_DIR)/arp.o \
	$(KERNEL_NET_DIR)/ethernet.o \
	$(KERNEL_NET_DIR)/icmp.o \
	$(KERNEL_NET_DIR)/if.o \
	$(KERNEL_NET_DIR)/ipv4.o \
	$(KERNEL_NET_DIR)/loopback.o \
	$(KERNEL_NET_DIR)/misc.o \
	$(KERNEL_NET_DIR)/net.o \
	$(KERNEL_NET_DIR)/socket.o \
	$(KERNEL_NET_DIR)/udp.o
