# net makefile
KERNEL_NET_DIR := net

MY_SRCS += \
	$(KERNEL_NET_DIR)/arp.c \
	$(KERNEL_NET_DIR)/ethernet.c \
	$(KERNEL_NET_DIR)/icmp.c \
	$(KERNEL_NET_DIR)/if.c \
	$(KERNEL_NET_DIR)/ipv4.c \
	$(KERNEL_NET_DIR)/loopback.c \
	$(KERNEL_NET_DIR)/misc.c \
	$(KERNEL_NET_DIR)/net.c \
	$(KERNEL_NET_DIR)/net_control.c \
	$(KERNEL_NET_DIR)/net_timer.c \
	$(KERNEL_NET_DIR)/socket.c \
	$(KERNEL_NET_DIR)/socket_dev.c \
	$(KERNEL_NET_DIR)/udp.c \
	$(KERNEL_NET_DIR)/tcp.c
