# libm common_source makefile
LIBM_COMMON_SOURCE_DIR := common_source

MY_OBJS += \
	$(LIBM_COMMON_SOURCE_DIR)/acosh.o \
	$(LIBM_COMMON_SOURCE_DIR)/asincos.o \
	$(LIBM_COMMON_SOURCE_DIR)/asinh.o \
	$(LIBM_COMMON_SOURCE_DIR)/atan.o \
	$(LIBM_COMMON_SOURCE_DIR)/cosh.o \
	$(LIBM_COMMON_SOURCE_DIR)/atanh.o \
	$(LIBM_COMMON_SOURCE_DIR)/erf.o \
	$(LIBM_COMMON_SOURCE_DIR)/exp.o \
	$(LIBM_COMMON_SOURCE_DIR)/exp__E.o \
	$(LIBM_COMMON_SOURCE_DIR)/expm1.o \
	$(LIBM_COMMON_SOURCE_DIR)/floor.o \
	$(LIBM_COMMON_SOURCE_DIR)/fmod.o \
	$(LIBM_COMMON_SOURCE_DIR)/gamma.o \
	$(LIBM_COMMON_SOURCE_DIR)/j0.o \
	$(LIBM_COMMON_SOURCE_DIR)/j1.o \
	$(LIBM_COMMON_SOURCE_DIR)/jn.o \
	$(LIBM_COMMON_SOURCE_DIR)/lgamma.o \
	$(LIBM_COMMON_SOURCE_DIR)/log.o \
	$(LIBM_COMMON_SOURCE_DIR)/log10.o \
	$(LIBM_COMMON_SOURCE_DIR)/log1p.o \
	$(LIBM_COMMON_SOURCE_DIR)/log__L.o \
	$(LIBM_COMMON_SOURCE_DIR)/pow.o \
	$(LIBM_COMMON_SOURCE_DIR)/sinh.o \
	$(LIBM_COMMON_SOURCE_DIR)/tanh.o
