KERNEL_BUS_MANAGERS_ADDONS_DIR := $(KERNEL_ADDONS_DIR)/bus_managers
KERNEL_BUS_MANAGERS_ADDONS_BUILD_DIR := $(KERNEL_ADDONS_BUILD_DIR)/bus_managers

# include sub makefiles
include $(addsuffix /makefile, $(addprefix $(KERNEL_BUS_MANAGERS_ADDONS_DIR)/, \
	isa \
))
