KERNEL_DEV_DISK_SCSI_ADDONS_DIR := $(KERNEL_DEV_DISK_ADDONS_DIR)/scsi
KERNEL_DEV_DISK_SCSI_ADDONS_BUILD_DIR := $(KERNEL_DEV_DISK_ADDONS_BUILD_DIR)/scsi

# include sub makefiles
include $(addsuffix /makefile, $(addprefix $(KERNEL_DEV_DISK_SCSI_ADDONS_DIR)/, \
	scsi_dsk \
))
