# arch i386 makefile
KERNEL_ARCH_I386_DIR := arch/i386

MY_SRCS += \
	$(KERNEL_ARCH_I386_DIR)/arch_cpu.c \
	$(KERNEL_ARCH_I386_DIR)/arch_dbg_console.c \
	$(KERNEL_ARCH_I386_DIR)/arch_debug.c \
	$(KERNEL_ARCH_I386_DIR)/arch_elf.c \
	$(KERNEL_ARCH_I386_DIR)/arch_faults.c \
	$(KERNEL_ARCH_I386_DIR)/arch_i386.S \
	$(KERNEL_ARCH_I386_DIR)/arch_interrupts.S \
	$(KERNEL_ARCH_I386_DIR)/arch_int.c \
	$(KERNEL_ARCH_I386_DIR)/arch_smp.c \
	$(KERNEL_ARCH_I386_DIR)/arch_time.c \
	$(KERNEL_ARCH_I386_DIR)/arch_timer.c \
	$(KERNEL_ARCH_I386_DIR)/arch_thread.c \
	$(KERNEL_ARCH_I386_DIR)/arch_selector.c \
	$(KERNEL_ARCH_I386_DIR)/arch_vm.c \
	$(KERNEL_ARCH_I386_DIR)/arch_vm_translation_map.c
