# dev i386 ps2mouse makefile
MY_SRCDIR := $(GET_LOCAL_DIR)
MY_TARGETDIR := $(call TOBUILDDIR, $(MY_SRCDIR))
MY_TARGET := $(MY_TARGETDIR)/mouse

MY_SRCS := \
    ps2mouse.c \

include templates/kernel_addons.mk
