# arch x86_64 makefile
KERNEL_ARCH_X86_64_DIR := arch/x86_64

MY_OBJS += \
	$(KERNEL_ARCH_I386_DIR)/arch_cpu.o \
	$(KERNEL_ARCH_I386_DIR)/arch_dbg_console.o \
	$(KERNEL_ARCH_I386_DIR)/arch_debug.o \
	$(KERNEL_ARCH_I386_DIR)/arch_elf.o \
	$(KERNEL_ARCH_I386_DIR)/arch_faults.o \
	$(KERNEL_ARCH_I386_DIR)/arch_i386.o \
	$(KERNEL_ARCH_I386_DIR)/arch_interrupts.o \
	$(KERNEL_ARCH_I386_DIR)/arch_int.o \
	$(KERNEL_ARCH_I386_DIR)/arch_smp.o \
	$(KERNEL_ARCH_I386_DIR)/arch_time.o \
	$(KERNEL_ARCH_I386_DIR)/arch_timer.o \
	$(KERNEL_ARCH_I386_DIR)/arch_thread.o \
	$(KERNEL_ARCH_I386_DIR)/arch_selector.o \
	$(KERNEL_ARCH_I386_DIR)/arch_vm.o \
	$(KERNEL_ARCH_I386_DIR)/arch_vm_translation_map.o
