# app makefile
MY_SRCDIR := $(GET_LOCAL_DIR)

MY_SRCS := \
	InputDevice.cpp \
	InputServer.cpp \
	KeyboardDevice.cpp \
	main.cpp \
	PS2Device.cpp

MY_LIBS := -lc -lnewos -lsupc++

include templates/app.mk

