# dev rtl8139 makefile
MY_SRCDIR := $(GET_LOCAL_DIR)
MY_TARGETDIR := $(call TOBUILDDIR, $(MY_SRCDIR))
MY_TARGET := $(MY_TARGETDIR)/rtl8169

MY_SRCS := \
	rtl8169.c \
	rtl8169_dev.c

include templates/kernel_addons.mk
