# app makefile
MY_SRCDIR := $(GET_LOCAL_DIR)

MY_SRCS := \
	main.cpp \
	PS2Mouse.cpp \
	Renderer_16bpp.cpp \
	Renderer_vesa.cpp \
	Region.cpp \
	GraphicsContext.cpp \
	Window.cpp \
	WindowManager.cpp

MY_LIBS := -lc -lwin -lnewos -lsupc++

include templates/app.mk
