# dev ns83820 makefile
MY_SRCDIR := $(GET_LOCAL_DIR)
MY_TARGETDIR := $(call TOBUILDDIR, $(MY_SRCDIR))
MY_TARGET := $(MY_TARGETDIR)/ns83820

MY_SRCS := \
	ns83820.c \
	ns83820_dev.c

include templates/kernel_addons.mk
