
APPS_DIR := apps

include $(addsuffix /makefile, $(addprefix $(APPS_DIR)/, \
	false \
	fibo \
	fortune \
	init \
	ls \
	mount \
	rld \
	rldtest \
	shell \
	testapp \
	true \
	unmount \
	vmtest \
	vtcolors \
	rm \
	ps \
	top \
	nettest \
	irc \
	consoled \
	socketd \
	telnetd \
	inputd \
	window_server \
	guiapp \
))


