
APPS_DIR := apps

include $(addsuffix /makefile, $(addprefix $(APPS_DIR)/, \
	false \
	fibo \
	fortune \
	init \
	ls \
	mount \
	rld \
	rldtest \
	shell \
	testapp \
	true \
	unmount \
	vmtest \
	rm \
	ps \
	top \
	nettest \
	irc \
	consoled \
))


