# vm makefile
KERNEL_VM_DIR := vm

MY_SRCS += \
	$(KERNEL_VM_DIR)/vm.c \
	$(KERNEL_VM_DIR)/vm_cache.c \
	$(KERNEL_VM_DIR)/vm_daemons.c \
	$(KERNEL_VM_DIR)/vm_page.c \
	$(KERNEL_VM_DIR)/vm_store_anonymous_noswap.c \
	$(KERNEL_VM_DIR)/vm_store_device.c \
	$(KERNEL_VM_DIR)/vm_store_null.c \
	$(KERNEL_VM_DIR)/vm_store_vnode.c \
	$(KERNEL_VM_DIR)/vm_tests.c
