# vm makefile
KERNEL_VM_DIR := vm

MY_OBJS += \
	$(KERNEL_VM_DIR)/vm.o \
	$(KERNEL_VM_DIR)/vm_cache.o \
	$(KERNEL_VM_DIR)/vm_daemons.o \
	$(KERNEL_VM_DIR)/vm_page.o \
	$(KERNEL_VM_DIR)/vm_store_anonymous_noswap.o \
	$(KERNEL_VM_DIR)/vm_store_device.o \
	$(KERNEL_VM_DIR)/vm_store_null.o \
	$(KERNEL_VM_DIR)/vm_store_vnode.o \
	$(KERNEL_VM_DIR)/vm_tests.o
