# libc stdlib makefile
LIBC_STDLIB_DIR := stdlib

MY_SRCS += \
	$(LIBC_STDLIB_DIR)/abort.c \
	$(LIBC_STDLIB_DIR)/assert.c \
	$(LIBC_STDLIB_DIR)/atoi.c \
	$(LIBC_STDLIB_DIR)/bsearch.c \
	$(LIBC_STDLIB_DIR)/exit.c \
	$(LIBC_STDLIB_DIR)/getenv.c \
	$(LIBC_STDLIB_DIR)/getopt.c \
	$(LIBC_STDLIB_DIR)/heapsort.c \
	$(LIBC_STDLIB_DIR)/merge.c \
	$(LIBC_STDLIB_DIR)/qsort.c \
	$(LIBC_STDLIB_DIR)/radixsort.c \
	$(LIBC_STDLIB_DIR)/rand.c \
	$(LIBC_STDLIB_DIR)/random.c \
	$(LIBC_STDLIB_DIR)/strtod.c \
	$(LIBC_STDLIB_DIR)/strtol.c \
	$(LIBC_STDLIB_DIR)/strtoll.c \
	$(LIBC_STDLIB_DIR)/strtoul.c \
	$(LIBC_STDLIB_DIR)/strtoull.c

