# libc stdlib makefile
LIBC_STDLIB_DIR := stdlib

MY_OBJS += \
	$(LIBC_STDLIB_DIR)/abort.o \
	$(LIBC_STDLIB_DIR)/assert.o \
	$(LIBC_STDLIB_DIR)/atoi.o \
	$(LIBC_STDLIB_DIR)/bsearch.o \
	$(LIBC_STDLIB_DIR)/exit.o \
	$(LIBC_STDLIB_DIR)/getenv.o \
	$(LIBC_STDLIB_DIR)/getopt.o \
	$(LIBC_STDLIB_DIR)/heapsort.o \
	$(LIBC_STDLIB_DIR)/merge.o \
	$(LIBC_STDLIB_DIR)/qsort.o \
	$(LIBC_STDLIB_DIR)/radixsort.o \
	$(LIBC_STDLIB_DIR)/rand.o \
	$(LIBC_STDLIB_DIR)/random.o \
	$(LIBC_STDLIB_DIR)/strtod.o \
	$(LIBC_STDLIB_DIR)/strtol.o \
	$(LIBC_STDLIB_DIR)/strtoll.o \
	$(LIBC_STDLIB_DIR)/strtoul.o \
	$(LIBC_STDLIB_DIR)/strtoull.o

